# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - main
    

name: render-readme.yaml

permissions: read-all

jobs:
  render-readme-qmd:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true 

      - name: Render README.qmd and Commit Results
        run: |
          Rscript -e 'install.packages("rmarkdown")'
          Rscript -e 'install.packages("tidyverse")'
          Rscript -e 'install.packages("sparklyr")'
          Rscript -e 'install.packages("pysparklyr")'
          Rscript -e 'install.packages("knitr")'
          quarto render README.qmd
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit . -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
