# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - main
    

name: render-readme.yaml

permissions: read-all

jobs:
  render-readme-qmd:
    runs-on: ubuntu-latest
    env:
      TESTE: ${{ secrets.TESTE }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install libcurl4-openssl-dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Create and populate .Renviron file
        run: |
          echo MY_SECRET="$TESTE" >> ~/.Renviron

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true 

      - name: Render README.qmd and Commit Results
        run: |
          Rscript -e 'install.packages("webshot2", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
          Rscript -e 'install.packages("rmarkdown", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
          Rscript -e 'install.packages("tidyverse", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
          Rscript -e 'install.packages("sparklyr", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
          Rscript -e 'install.packages("pysparklyr", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
          Rscript -e 'install.packages("knitr", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
          Rscript -e 'install.packages("plotly", repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))'
          Rscript -e 'webshot2::install_phantomjs()'
          quarto render README.qmd
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit . -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
